### ISSUE TITLE
Clobbers click handlers in certain web applications

### ISSUE THREAD

**Issue by erictsai6** [rmiyashiro/CandyCaneId#1]
Big fan of the plugin, but I did notice that it seems to be clobbering the click handlers in specific web application.

Specifically when I try to use it with splunk I no longer can click on an object id and easily include / filter out that ID.

**Comment by rmiyashiro** [comment]
Should be fixed in the next release: https://github.com/rmiyashiro/CandyCaneId/commit/669f34003b22ec5966391277e6b0e31eb6c29410
