### ISSUE TITLE
Candy cane plugin breaks JIRA editing comments

### ISSUE THREAD

**Issue by erictsai6** [rmiyashiro/CandyCaneId#2]
We are using a self-hosted JIRA server so I don't know if cloud JIRA will suffer from these same issues.  I have to disable the entire plugin in order to get editing JIRA comments back to normal.

**Comment by rmiyashiro** [comment]
Should be fixed in v0.0.5: 
https://github.com/rmiyashiro/CandyCaneId/commit/31da03b1260de964fc37362eae3eec6f84d88068
